CUDA_VISIBLE_DEVICES="6,7" \
accelerate launch train_controlnext_img2img.py \
--pretrained_model_name_or_path "stabilityai/stable-diffusion-xl-base-1.0" \
--pretrained_vae_model_name_or_path "madebyollin/sdxl-vae-fp16-fix" \
--variant fp16 \
--use_safetensors \
--output_dir "train/example" \
--logging_dir "logs" \
--resolution 1024 \
--gradient_checkpointing \
--set_grads_to_none \
--proportion_empty_prompts 0.2 \
--controlnet_scale_factor 1.0 \
--train_batch_size 2 \
--save_weights_increaments \
--mixed_precision fp16 \
--enable_xformers_memory_efficient_attention \
--dataset_name "/data/lihaochen/projects/EzRelight" \
--data_files "stage1.parquet" \
--cache_dir "/data3/lihaochen/BGRelight/stage1_cache" \
--caption_column "caption"