CUDA_VISIBLE_DEVICES="7" \
accelerate launch --num_processes 1 val_video.py \
--pretrained_model_name_or_path "stabilityai/stable-diffusion-xl-base-1.0" \
--pretrained_vae_model_name_or_path "madebyollin/sdxl-vae-fp16-fix" \
--variant fp16 \
--use_safetensors \
--output_dir "/data2/lihaochen/EzRelight_chps/video/try_0331" \
--logging_dir "logs" \
--resolution 1024 \
--gradient_checkpointing \
--set_grads_to_none \
--proportion_empty_prompts 0.2 \
--controlnet_scale_factor 1.0 \
--train_batch_size 1 \
--mixed_precision fp16 \
--checkpointing_steps 2000 \
--enable_xformers_memory_efficient_attention \
--dataset_name "/data/lihaochen/projects/EzRelight" \
--data_files "video_test.parquet" \
--cache_dir "/data3/lihaochen/BGRelight/video_cache" \
--caption_column "caption" \
--stage1_chp_path "/data2/lihaochen/EzRelight_chps/video/try_0331/checkpoints/final"